name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore TestDb/TestDb.sln
    - name: Build
      run: dotnet build  TestDb/TestDb.sln --no-restore
